# Generated by Django 3.2.9 on 2022-06-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(choices=[('MMIA', 'Murtala Muhammed International Airport.'), ('AIIAE', 'Akanu Ibiam International Aiport, Enugu.'), ('IA', 'Ibadan Airport.'), ('PHIC', 'Port Harcourt International Airport.'), ('KIA', 'Kaduna International Airport.'), ('IIA', 'Ilorin International Airport.'), ('MEIA', 'Margaret Ekpo International Airport.'), ('AIA', 'Asaba International Airport.'), ('AA', 'Akure Airport.'), ('SMICA', 'Sam M+bakwa International Cargo Airport.')], max_length=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(choices=[('MMIA', 'LOS'), ('AIIAE', 'ENU'), ('IA', 'IBA'), ('PHIC', 'PHC'), ('KIA', 'KAD'), ('IIA', 'ILR'), ('MEIA', 'CBQ'), ('AIA', 'ABB'), ('AA', 'AKR'), ('SMICA', 'QOW')], max_length=5),
        ),
    ]
