# Generated by Django 3.2.9 on 2022-06-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20220630_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(blank=True, choices=[('MMIA', 'LOS'), ('AIIAE', 'ENU'), ('IA', 'IBA'), ('PHIC', 'PHC'), ('KIA', 'KAD'), ('IIA', 'ILR'), ('MEIA', 'CBQ'), ('AIA', 'ABB'), ('AA', 'AKR'), ('SMICA', 'QOW')], max_length=5),
        ),
    ]
